name: EnderButt
version: '1.0-SNAPSHOT'
main: me.bludenz.enderbutt.EnderButt
authors: [ Bludenz ]
description: EnderButt Gadget
commands:
  enderbutt:
    usage: /enderbutt
    description: Gives Enderbutt
